### ISSUE TITLE
add lastComplete

### ISSUE THREAD

**Issue by paoloricciuti** [mainmatter/svelte-concurrency#84]

**Comment by paoloricciuti** [comment]
I think `lastComplete` is one that was not cancelled either if it was an error or not...i don't know if this is useful 😄

**Comment by beerinho** [comment]
To be honest I don't think it is useful, we have `last`, `lastErrored`, `lastSuccessful` & `lastCanceled`, I think that covers everything we need

**Comment by beerinho** [comment]
Closing as I don't think this is necessary
