### ISSUE TITLE
cancellation breaks `enqueue` and `drop` tasks

### ISSUE THREAD

**Issue by beerinho** [mainmatter/svelte-concurrency#93]
The branch `cancellation-bug` has the failing tests on it.

For some reason, cancelling the task once stops it from being able to rerun at all. This is the case for `enqueue`, `drop` and `keepLatest` type tasks

**Comment by paoloricciuti** [comment]
What do you mean by this?

**Comment by beerinho** [comment]
@paoloricciuti, I just updated the title and description, hopefully it makes sense. This was just something I noticed, I haven't looked into it at all yet

**Comment by paoloricciuti** [comment]
> @paoloricciuti, I just updated the title and description, hopefully it makes sense. This was just something I noticed, I haven't looked into it at all yet

Are you working on this or can i work on this?
